project 3 update smoke test fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -371,44 +371,67 @@ jobs:
       - revert-migrations
 
   smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - run:
-          name: "install awscli"
-          command: | 
-            install_awscli
-            install_nodejs
+        docker:
+            # Lightweight Docker image
+            - image: python:3.7-alpine3.11
+              environment:
+                  NODE_ENV: "local"
+                  VERSION: "1"
+                  ENVIRONMENT: "production"
+                  TYPEORM_CONNECTION: $TYPEORM_CONNECTION
+                  TYPEORM_HOST: $TYPEORM_HOST
+                  TYPEORM_USERNAME: $TYPEORM_USERNAME
+                  TYPEORM_PASSWORD: $TYPEORM_PASSWORD
+                  TYPEORM_DATABASE: $TYPEORM_DATABASE
+                  TYPEORM_PORT: $TYPEORM_PORT
+                  TYPEORM_ENTITIES: $TYPEORM_ENTITIES
+        steps:
+            # Checkout code from git
+            - checkout
+            - attach_workspace:
+                  at: ~/
+            - run:
+                  name: Install dependencies
+                  command: |
+                      apk add --update curl
+                      pip install awscli
+            - run:
+                  name: Waiting for the server to start running
+                  command: sleep 2m
+            - run:
+                  name: Backend smoke test.
+                  command: |
+                      export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                      --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                      --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+                      --output text)
+                      export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+                      echo $API_URL
+                      if curl -s $API_URL/api/status | grep "ok"
+                      then
+                      exit 0
+                      else
+                      exit 1
+                      fi
+                      
+            - run:
+                  name: Frontend smoke test.
+                  command: |
+                      URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+                      echo ${URL} 
+                      if curl -s ${URL} | grep "Welcome"
+                      then
+                      # Change this to 0 after the job fails
+                      return 0
+                      else
+                      return 1
+                      fi
+           # Here's where you will add some code to rollback on failure
+            # - destroy-environment:
+                  # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+            # - revert-migrations:
+                  # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-      - run:
-          name: Backend smoke test.
-          command: |
-            sudo apt install curl -y
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            echo $API_URL
-            if curl --connect-timeout 5 "${API_URL}/api/status" -v | grep "ok"; then exit 0; else exit 1; fi
-
-      - run:
-          name: Frontend smoke test.
-          command: |
-            sudo apt install curl -y
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE -v | grep "Welcome"
-            then
-              # This is the intentional error, if "Welcome" is indeed in the response this step will exit with exit code 1
-              exit 0
-            else
-              exit 1
-            fi
-
-      # - destroy-environment
-      # - revert-migrations
 
 #   cloudfront-update:
 #     docker:
