project 3 update smoke test fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -371,41 +371,40 @@ jobs:
       - revert-migrations
 
   smoke-test:
-    docker: 
-      - image: python:3.7-alpine3.11
-    steps:  
+    docker:
+      - image: cimg/base:stable
+    steps:
       - checkout
-      - run: 
-          name: Install dependencies
+      - install_awscli
+      - install_nodejs
+
+      - run:
+          name: Backend smoke test.
           command: |
-            apk add --update curl
-            pip install awscli
-            pip install nodejs
-            pip install npm 
-      - run: 
-          name: Backend smoke test
+            sudo apt install curl -y
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+
+            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+            echo $API_URL
+            if curl --connect-timeout 5 "${API_URL}/api/status" -v | grep "ok"; then exit 0; else exit 1; fi
+
+      - run:
+          name: Frontend smoke test.
           command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text)
-            echo "$BACKEND_IP"
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok" 
+            sudo apt install curl -y
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE -v | grep "Welcome"
             then
-              return 0
+              # This is the intentional error, if "Welcome" is indeed in the response this step will exit with exit code 1
+              exit 0
             else
-              return 1
+              exit 1
             fi
-      
-      - run: 
-          name: Frontend smoke test
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com"
-            echo ${URL}
-            if curl -s ${URL} | grep "Welcome"; then  exit 0; else exit 1; fi
-      # - destroy-environment  
+
+      # - destroy-environment
       # - revert-migrations
 
 #   cloudfront-update:
